package com.sabre.bigdata.smav2.util;

public enum BadRecordCounters {
	RECORDS_NUMBER,
	EMPTY_REQUEST,
	EMPTY_ORIG_DEST_INFO,
	NULL_ORIG_DEST_RECS,
	WRONG_OUT_DEP_DATE,
	OUT_DEP_DATE_NOT_IN_RANGE,
	WRONG_IN_DEP_DATE,
	IN_DEP_DATE_NOT_IN_RANGE,
	NO_LIFE_FLIGHT,
	OPEN_JAW_FLIGHTS,
	EMPTY_SHOP_DATE,
	EMPTY_ITINERARIES,
	WRONG_POS_BOOKING_CHANNEL,
	WRONG_PCC_LEN,
	INCORRECT_PCC,
	WRONG_PCC_EXTENSION,
	UNKNOWN_TRIP_TYPE,
	EMPTY_FLIGHTS,
	NULL_FLIGHT,
	DIFFERENT_MARKETING_CARRIER,
	AIRPORT_MISMATCH
}
